spring:
  application:
    name: quote-server

  datasource:
    url: jdbc:mysql://localhost:3306/quoteline
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    enabled: false
app:
  kafka:
    topic:
      email: email-topic

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always