apiVersion: v1
kind: Service
metadata:
  name: quote-server
  namespace: quoteline-dev
spec:
  selector:
    app: quote-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP